### ISSUE TITLE
Unsupported build state: "started"

### ISSUE THREAD

**Issue by bpasero** [felixrieseberg/vsc-travis-ci-status#11]
In https://github.com/felixrieseberg/vsc-travis-ci-status/blob/master/travis-status.ts#L71 an error is raised as soon as travis sends the state "started" which seems like a valid build state 👍

**Comment by felixrieseberg** [comment]
Merci, I'll fix that real quick

**Comment by bpasero** [comment]
Cool, thanks 👍
