### ISSUE TITLE
Auto update status

### ISSUE THREAD

**Issue by dylanparry** [felixrieseberg/vsc-travis-ci-status#18]
Hi,

I'm not sure if it's supposed to do this already, but it would be nice if the status bar icon would automatically update itself every so often so I don't have to click on it to see the status of the current build.  I had a quick look at the source code, but couldn't see anything that's supposed to do this and it doesn't appear to at the moment—unless my installation is buggy and it is supposed to!

I don't know if it's possible, but maybe it could automatically begin requesting a status update from Travis when a Git push has been performed, and continue requesting an update until the build has completed? If not, then just the ability to set a time interval in the settings that makes the extension update the status every _x_ seconds would be great too 😄

**Comment by felixrieseberg** [comment]
I think it's a good idea - I'd gladly merge a pull request. Would you be interested in quickly hacking it in?

**Comment by dylanparry** [comment]
Sure. I'll take a look at it.

**Comment by dylanparry** [comment]
Hi, meant to say a week ago that I'd made a PR to add this feature. I gave it a little testing on my machine and it appeared to work well, although I'm sure it could be improved. Thanks.
