### ISSUE TITLE
Private repositories hosted on magnum.travis-ci.com don't work

### ISSUE THREAD

**Issue by irq** [felixrieseberg/vsc-travis-ci-status#4]
It would be great if this extension would work with repositories hosted on https://magnum.travis-ci.com as well as https://travis-ci.org.

Could be via a setting.

**Comment by phacks** [comment]
I'd like to have this setting too !

**Comment by felixrieseberg** [comment]
Good idea - if anybody wants to submit a PR, I'd gladly merge it!

**Comment by gdziadkiewicz** [comment]
I'd like to implement that and did some tests already. Private Travis instances require authentication(can be done either by GitHub user and password or by authentication token). How would you go about storing them?
